<hh> ::=  <acceptance>
<acceptance> ::= <acceptance-terminal> | <acceptance> <op> <acceptance> | (<acceptance> <op> <acceptance>)
<acceptance-terminal> ::= "Delta" | "PF" | "CI" | "TI"
<op> ::= "*" | "/" | "+" | "-"